# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Upload Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Upload Staging
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.TEST_FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.TEST_FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.TEST_FTP_PASSWORD }}
          LOCAL_DIR: ./
          REMOTE_DIR: /public_html/
